version: '3.8'

services:
  db:
    image: postgres:16
    platform: linux/amd64
    environment:
      POSTGRES_USER: cocktail_postgres_user
      POSTGRES_PASSWORD: cocktail_postgres_password
      POSTGRES_DB: cocktail_hub_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rm -rf tmp/cache && rm -f tmp/sockets/* && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: cocktail_postgres_user
      POSTGRES_PASSWORD: cocktail_postgres_password
      POSTGRES_DB: cocktail_hub_development
      DATABASE_URL: postgres://cocktail_postgres_user:cocktail_postgres_password@db/cocktail_hub_development

volumes:
  postgres-data: