require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.6
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'public/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/IndentationWidth:
  Width: 2

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 25

Style/ClassAndModuleChildren:
  EnforcedStyle: nested