name: Run RSpec Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Rubyをセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: 環境変数の設定
        run: |
          echo "RAILS_ENV=test" >> $GITHUB_ENV
          echo "DATABASE_URL=postgres://postgres:password@localhost:5432/myapp_test" >> $GITHUB_ENV

      - name: Node.js をセットアップ（必要な場合）
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Yarn パッケージをインストール（必要な場合）
        run: yarn install --frozen-lockfile

      - name: データベースをセットアップ
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: RSpec を実行
        run: bundle exec rspec
