name: Run RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.6'

      - name: Install Bundler
        run: gem install bundler

      - name: Install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips42

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec
